### ISSUE TITLE
Error in observer.error

### ISSUE THREAD

**Issue by hongbo-miao** [learnapollo/pokedex-angular#3]
When the app runs, the error below shows in the console. And the screen only shows Loading.

```
Error in observer.error 
Error
    at new ApolloError (http://localhost:3000/main.bundle.js:32343:22)
    at http://localhost:3000/main.bundle.js:31824:39
    at http://localhost:3000/main.bundle.js:32308:25
    at Array.forEach (native)
    at http://localhost:3000/main.bundle.js:32305:27
    at http://localhost:3000/main.bundle.js:84364:11
    at baseForOwn (http://localhost:3000/main.bundle.js:34975:20)
    at forOwn (http://localhost:3000/main.bundle.js:85963:20)
    at QueryManager.broadcastQueries (http://localhost:3000/main.bundle.js:32303:9)
    at Array.<anonymous> (http://localhost:3000/main.bundle.js:31734:23)
```

**Comment by marktani** [comment]
You have to make sure to replace the `__PROJECT_ID__` with an actual endpoint to a GraphQL server [here](https://github.com/learnapollo/pokedex-angular/blob/master/playground/src/app/client.ts#L7).

Also you have to replace `__NAME__` with the trainer name [here](https://github.com/learnapollo/pokedex-angular/blob/master/playground/src/app/pokedex.component.ts#L11)

Have you signed up at http://learnapollo.com with GitHub? Then you can just click the `Download Example` button [here](https://www.learnapollo.com/tutorial-angular/angular-playground).

**Comment by hongbo-miao** [comment]
Oh, sorry, I don't know that. Maybe add in readme? I thought after running, it will just work.
I will check http://learnapollo.com and do again.

**Comment by marktani** [comment]
Good idea, I will update the README.

**Comment by hongbo-miao** [comment]
Nice, after using own version, now it works.
